# Generated by Django 5.0.2 on 2024-02-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
